spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
tripplanner:
  default:
    kilometers: 20
    days: 1