create table item
(
    id                 bigint generated by default as identity,
    name               varchar(255),
    required_amount integer,
    required_amount_frequency varchar(255) check (required_amount_frequency in ('PER_DAY', 'PER_TRIP', 'PER_TRIP_SINCE_DAY_2')),
    primary key (id)
);

create table item_season
(
    id              bigint generated by default as identity,
    item_id         bigint,
    month_of_season varchar(255) check (month_of_season in
                                        ('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST',
                                         'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER')),
    primary key (id)
);